package movieStatsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-12-15T05:57:05.774Z
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "IMovieStatsService", 
                  wsdlLocation = "http://localhost:8081/StatsRequest?wsdl",
                  targetNamespace = "http://services/") 
public class IMovieStatsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services/", "IMovieStatsService");
    public final static QName IMovieStatsPort = new QName("http://services/", "IMovieStatsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/StatsRequest?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IMovieStatsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/StatsRequest?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IMovieStatsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IMovieStatsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMovieStatsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IMovieStatsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IMovieStatsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IMovieStatsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IMovieStats
     */
    @WebEndpoint(name = "IMovieStatsPort")
    public IMovieStats getIMovieStatsPort() {
        return super.getPort(IMovieStatsPort, IMovieStats.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMovieStats
     */
    @WebEndpoint(name = "IMovieStatsPort")
    public IMovieStats getIMovieStatsPort(WebServiceFeature... features) {
        return super.getPort(IMovieStatsPort, IMovieStats.class, features);
    }

}
