
package movieStatsService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Scanner;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-12-15T05:57:05.759Z
 * Generated source version: 2.5.1
 * 
 */
public final class IMovieStats_IMovieStatsPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services/", "IMovieStatsService");

    private IMovieStats_IMovieStatsPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IMovieStatsService.WSDL_LOCATION;
              
        IMovieStatsService ss = new IMovieStatsService(wsdlURL, SERVICE_NAME);
        IMovieStats port = ss.getIMovieStatsPort();  
        
        {
        System.out.println("Invoking get...");
        Scanner sc = new Scanner(System.in);
        int option;
        
        do {
            System.out.println("1. Total Processed Movies");
            System.out.println("2. Movies Processed by Categorie");
            System.out.println("3. Digest emails sent");
            System.out.println("4. Non-Digest emails sent");
            option = sc.nextInt();
        } while (option < 1 || option > 4);
        
        java.lang.String _get__return = port.get(option);
        System.out.println("get.result=" + _get__return);


        }

        System.exit(0);
    }

}
