package subscribeFavoritesService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-12-15T04:23:21.892Z
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "ISubscribeFavoritesService", 
                  wsdlLocation = "http://localhost:8081/MovieSubscribe?wsdl",
                  targetNamespace = "http://services/") 
public class ISubscribeFavoritesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services/", "ISubscribeFavoritesService");
    public final static QName ISubscribeFavoritesPort = new QName("http://services/", "ISubscribeFavoritesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/MovieSubscribe?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ISubscribeFavoritesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/MovieSubscribe?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ISubscribeFavoritesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISubscribeFavoritesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISubscribeFavoritesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISubscribeFavoritesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISubscribeFavoritesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ISubscribeFavoritesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ISubscribeFavorites
     */
    @WebEndpoint(name = "ISubscribeFavoritesPort")
    public ISubscribeFavorites getISubscribeFavoritesPort() {
        return super.getPort(ISubscribeFavoritesPort, ISubscribeFavorites.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISubscribeFavorites
     */
    @WebEndpoint(name = "ISubscribeFavoritesPort")
    public ISubscribeFavorites getISubscribeFavoritesPort(WebServiceFeature... features) {
        return super.getPort(ISubscribeFavoritesPort, ISubscribeFavorites.class, features);
    }

}
