package subscribeFavoritesService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-12-15T04:23:21.876Z
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://services/", name = "ISubscribeFavorites")
@XmlSeeAlso({ObjectFactory.class})
public interface ISubscribeFavorites {

    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "Add", targetNamespace = "http://services/", className = "subscribeFavoritesService.Add")
    @WebMethod(operationName = "Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://services/", className = "subscribeFavoritesService.AddResponse")
    public java.lang.String add(
        @WebParam(name = "Email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "Type", targetNamespace = "")
        java.lang.String type
    );

    @WebResult(name = "Data", targetNamespace = "")
    @RequestWrapper(localName = "Remove", targetNamespace = "http://services/", className = "subscribeFavoritesService.Remove")
    @WebMethod(operationName = "Remove")
    @ResponseWrapper(localName = "RemoveResponse", targetNamespace = "http://services/", className = "subscribeFavoritesService.RemoveResponse")
    public java.lang.String remove(
        @WebParam(name = "Email", targetNamespace = "")
        java.lang.String email
    );
}
